networks:
  AVAX: 'https://rpc.ankr.com/avalanche'
  ETH: 'https://rpc.ankr.com/eth'
  POLY: 'https://rpc.ankr.com/polygon'
  BSC: 'https://bscrpc.com'
  CRO: 'https://evm-cronos.crypto.org'
  FTM: 'https://rpc.ftm.tools'
  ONE: 'https://api.harmony.one'
  HECO: 'https://http-mainnet.hecochain.com'
  ARB: 'https://arb1.arbitrum.io/rpc'
contract:
  address: '0x66357dCaCe80431aee0A7507e2E361B7e2402370'
  network: 'AVAX'
  abi: '[{"inputs":[{"internalType":"address","name":"initialLogic","type":"address"},{"internalType":"address","name":"initialAdmin","type":"address"},{"internalType":"bytes","name":"_data","type":"bytes"}],"stateMutability":"payable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"implementation","type":"address"}],"name":"Upgraded","type":"event"},{"stateMutability":"payable","type":"fallback"},{"inputs":[],"name":"admin","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"implementation","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"}],"name":"upgradeTo","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"upgradeToAndCall","outputs":[],"stateMutability":"payable","type":"function"},{"stateMutability":"payable","type":"receive"}]'